/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/ZkKnvEyLzPF
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"

export default function GalleryComponent() {
  return (
    <div className="container mx-auto py-12 px-4 sm:px-6 lg:px-8">
      <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
        <div className="relative group overflow-hidden rounded-lg">
          <img
            src="/placeholder.svg"
            alt="Gallery Image"
            width={400}
            height={400}
            className="w-full h-60 object-cover transition-transform duration-300 group-hover:scale-105"
            style={{ aspectRatio: "400/400", objectFit: "cover" }}
          />
          <div className="absolute inset-0 bg-black/50 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity duration-300">
            <div className="text-white text-center">
              <h3 className="text-lg font-semibold mb-2">Sunset Landscape</h3>
              <p className="text-sm">Breathtaking view of the sunset.</p>
            </div>
          </div>
        </div>
        <div className="relative group overflow-hidden rounded-lg">
          <img
            src="/placeholder.svg"
            alt="Gallery Image"
            width={400}
            height={400}
            className="w-full h-60 object-cover transition-transform duration-300 group-hover:scale-105"
            style={{ aspectRatio: "400/400", objectFit: "cover" }}
          />
          <div className="absolute inset-0 bg-black/50 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity duration-300">
            <div className="text-white text-center">
              <h3 className="text-lg font-semibold mb-2">Autumn Foliage</h3>
              <p className="text-sm">Vibrant colors of the changing seasons.</p>
            </div>
          </div>
        </div>
        <div className="relative group overflow-hidden rounded-lg">
          <img
            src="/placeholder.svg"
            alt="Gallery Image"
            width={400}
            height={400}
            className="w-full h-60 object-cover transition-transform duration-300 group-hover:scale-105"
            style={{ aspectRatio: "400/400", objectFit: "cover" }}
          />
          <div className="absolute inset-0 bg-black/50 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity duration-300">
            <div className="text-white text-center">
              <h3 className="text-lg font-semibold mb-2">City Skyline</h3>
              <p className="text-sm">Towering skyscrapers against the sky.</p>
            </div>
          </div>
        </div>
        <div className="relative group overflow-hidden rounded-lg">
          <img
            src="/placeholder.svg"
            alt="Gallery Image"
            width={400}
            height={400}
            className="w-full h-60 object-cover transition-transform duration-300 group-hover:scale-105"
            style={{ aspectRatio: "400/400", objectFit: "cover" }}
          />
          <div className="absolute inset-0 bg-black/50 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity duration-300">
            <div className="text-white text-center">
              <h3 className="text-lg font-semibold mb-2">Serene Lake</h3>
              <p className="text-sm">Peaceful reflection on the water.</p>
            </div>
          </div>
        </div>
        <div className="relative group overflow-hidden rounded-lg">
          <img
            src="/placeholder.svg"
            alt="Gallery Image"
            width={400}
            height={400}
            className="w-full h-60 object-cover transition-transform duration-300 group-hover:scale-105"
            style={{ aspectRatio: "400/400", objectFit: "cover" }}
          />
          <div className="absolute inset-0 bg-black/50 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity duration-300">
            <div className="text-white text-center">
              <h3 className="text-lg font-semibold mb-2">Misty Mountains</h3>
              <p className="text-sm">Majestic peaks shrouded in fog.</p>
            </div>
          </div>
        </div>
        <div className="relative group overflow-hidden rounded-lg">
          <img
            src="/placeholder.svg"
            alt="Gallery Image"
            width={400}
            height={400}
            className="w-full h-60 object-cover transition-transform duration-300 group-hover:scale-105"
            style={{ aspectRatio: "400/400", objectFit: "cover" }}
          />
          <div className="absolute inset-0 bg-black/50 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity duration-300">
            <div className="text-white text-center">
              <h3 className="text-lg font-semibold mb-2">Vibrant Flowers</h3>
              <p className="text-sm">Colorful blooms in a garden.</p>
            </div>
          </div>
        </div>
        <div className="relative group overflow-hidden rounded-lg">
          <img
            src="/placeholder.svg"
            alt="Gallery Image"
            width={400}
            height={400}
            className="w-full h-60 object-cover transition-transform duration-300 group-hover:scale-105"
            style={{ aspectRatio: "400/400", objectFit: "cover" }}
          />
          <div className="absolute inset-0 bg-black/50 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity duration-300">
            <div className="text-white text-center">
              <h3 className="text-lg font-semibold mb-2">Coastal Cliffs</h3>
              <p className="text-sm">Rugged beauty of the seaside.</p>
            </div>
          </div>
        </div>
        <div className="relative group overflow-hidden rounded-lg">
          <img
            src="/placeholder.svg"
            alt="Gallery Image"
            width={400}
            height={400}
            className="w-full h-60 object-cover transition-transform duration-300 group-hover:scale-105"
            style={{ aspectRatio: "400/400", objectFit: "cover" }}
          />
          <div className="absolute inset-0 bg-black/50 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity duration-300">
            <div className="text-white text-center">
              <h3 className="text-lg font-semibold mb-2">Starry Night Sky</h3>
              <p className="text-sm">Breathtaking view of the cosmos.</p>
            </div>
          </div>
        </div>
      </div>
      <div className="flex justify-center mt-8">
        <Button variant="outline" size="lg">
          <ChevronLeftIcon className="w-5 h-5 mr-2" />
          Previous
        </Button>
        <Button variant="outline" size="lg" className="ml-4">
          Next
          <ChevronRightIcon className="w-5 h-5 ml-2" />
        </Button>
      </div>
    </div>
  )
}

function ChevronLeftIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m15 18-6-6 6-6" />
    </svg>
  )
}


function ChevronRightIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m9 18 6-6-6-6" />
    </svg>
  )
}
